### ISSUE TITLE
Server-side error SELECT COUNT(*) FROM "malaria_post"

### ISSUE THREAD

**Issue by bphenriques** [systers/malaria-app-ios#14]
Using postman and using the default authentication mechanism the server responds with a error. On the mobile app client side it only says "No messages from peace corps" and the app doesn't crash which is good.

Dump:

ProgrammingError at /api/posts/
relation "malaria_post" does not exist
LINE 1: SELECT COUNT(*) FROM "malaria_post"
                             ^
Request Method:	GET
Request URL:	http://pc-web-dev.systers.org/api/posts/
Django Version:	1.6.5
Exception Type:	ProgrammingError
Exception Value:	
relation "malaria_post" does not exist
LINE 1: SELECT COUNT(*) FROM "malaria_post"
                             ^
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py in execute, line 53
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www/html/app-web-server/']
Server time:	Sat, 19 Sep 2015 12:09:03 -0500

**Comment by kangaroo5383** [comment]
@rosariorobinson would you know who can help with this server piece?

**Comment by bphenriques** [comment]
Wasn't (yet) tested the integration with the server with the current version of Alamofire (wasn't tested since swift 2 and since the server had issues).

Alamofire had a major update to 3.0. Might be interesting looking at it:
https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%203.0%20Migration%20Guide.md

**Comment by bphenriques** [comment]
In 8.4 works but on 9.X it doesn't work. It is a problem with the app. Weird.

**Comment by bphenriques** [comment]
Refer to issue #35
