### ISSUE TITLE
GSoC 2016 Widget: Next pill time and mark

### ISSUE THREAD

**Issue by bphenriques** [systers/malaria-app-ios#17]
Create a widget that displays when will the next pill should be taken.

It would be also great allowing to mark the pill directly in the widget ("Yes"/"No" as if the user took or not the pill on the current day).

**Comment by manas15** [comment]
What exactly is expected from this issue. I guess we already have this functionality in the app. 
@bphenriques Please help me understand your issue :)

**Comment by bphenriques** [comment]
Two widgets (or one) that:
- Say when the pill should be taken;
- Allows the user to say that he took the pill

This issue is already being handled by teodorc :)

**Comment by bphenriques** [comment]
There is already a version on the develop branch but can be improved to show when the next pill is

**Comment by bphenriques** [comment]
Fixed by #36 #38 . Thank you!
