### ISSUE TITLE
GSoC 2016 InfoHub only shows post on 8.X

### ISSUE THREAD

**Issue by bphenriques** [systers/malaria-app-ios#35]
Reproduce: run the app in 8.X and the info hub shows posts. In 8.4 it works fine

**Comment by tjnet** [comment]
Passing the headers into the request works. on iOS9.

[HTTPAdditionalHeaders is not successful on iOS9 · Issue #694 · Alamofire/Alamofire](https://github.com/Alamofire/Alamofire/issues/694)

 I will send you pull request.
